---
# sudo apt update && sudo apt install curl gnupg2 lsb-release
- name: Install dependencies for setting up sources
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - curl
    - gnupg2
    - lsb-release

# curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
- name: Setup ROS2 keys
  apt_key:
    url: "{{ ros_gpg_key_url }}"
    state: present

# sudo sh -c 'echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'
- name: Setup ROS2 sources
  apt_repository:
    repo: "deb {{ ros_repository_url }} {{ ansible_distribution_release }} main"
    state: present
    filename: ros2-latest

# sudo apt install ros-dashing-ros-base
- name: Install ROS2
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - "{{ 'ros-' + ros_distribution + '-' + ros_configuration }}"

# echo "source /opt/ros/dashing/setup.bash" >> ~/.bashrc
- name: Update .bashrc with /opt/ros/<ros_distribution>/setup.bash
  lineinfile:
    path: /home/{{ ros_user.name }}/.bashrc
    line: source /opt/ros/{{ ros_distribution }}/setup.bash
